// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecentChannel(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddRecentChannel'](arg1, arg2, arg3);
}

export function GetRecentChannels() {
  return window['go']['main']['App']['GetRecentChannels']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function IsBridgeRunning() {
  return window['go']['main']['App']['IsBridgeRunning']();
}

export function KillExistingBridges() {
  return window['go']['main']['App']['KillExistingBridges']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function ReadLogs() {
  return window['go']['main']['App']['ReadLogs']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartBridge() {
  return window['go']['main']['App']['StartBridge']();
}

export function StopBridge() {
  return window['go']['main']['App']['StopBridge']();
}
