// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddRulesToProject():Promise<string>;

export function AnswerQuestion(arg1:string,arg2:string):Promise<boolean>;

export function AutoCheckForUpdates():Promise<void>;

export function CheckForUpdates():Promise<string>;

export function ClearActivity():Promise<void>;

export function ConnectDetectedIDEs():Promise<Record<string, string>>;

export function ConnectIDE(arg1:string):Promise<string>;

export function DetectDiscordUser(arg1:string):Promise<main.DiscordLink>;

export function DetectSlackUser(arg1:string,arg2:string):Promise<main.SlackLink>;

export function DetectTelegramChat(arg1:string):Promise<main.TelegramChat>;

export function DisconnectIDE(arg1:string):Promise<string>;

export function DownloadUpdate(arg1:string):Promise<void>;

export function GetActivity():Promise<Array<main.Activity>>;

export function GetDiscordSettings():Promise<main.DiscordConfig>;

export function GetIDESnippet(arg1:string):Promise<string>;

export function GetNtfySettings():Promise<main.NtfyConfig>;

export function GetPublicURL():Promise<string>;

export function GetSlackManifest():Promise<string>;

export function GetSlackSettings():Promise<main.SlackConfig>;

export function GetState():Promise<main.AppState>;

export function GetTelegramSettings():Promise<main.TelegramConfig>;

export function GetWhatsAppSettings():Promise<Record<string, string>>;

export function HideWindow():Promise<void>;

export function IsBridgeRunning():Promise<boolean>;

export function ListIDEs():Promise<Array<main.IDEStatus>>;

export function LoadConfig():Promise<string>;

export function NewNtfyTopic():Promise<string>;

export function OpenDataFolder():Promise<void>;

export function OpenDiscordInvite(arg1:string):Promise<string>;

export function OpenSlackAppSetup():Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function QuitApp():Promise<void>;

export function ReadLogs():Promise<Array<string>>;

export function SaveDiscord(arg1:string,arg2:main.DiscordLink):Promise<string>;

export function SaveNtfy(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SaveSlack(arg1:string,arg2:string,arg3:main.SlackLink):Promise<string>;

export function SaveTelegram(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SaveWhatsApp(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SendTestQuestion():Promise<string>;

export function SetAtDesk(arg1:boolean):Promise<string>;

export function SetPopUp(arg1:boolean):Promise<string>;

export function ShowWindow():Promise<void>;

export function StartBridge():Promise<string>;

export function StartsMini():Promise<boolean>;

export function StopBridge():Promise<string>;
