// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRulesToProject() {
  return window['go']['main']['App']['AddRulesToProject']();
}

export function AutoCheckForUpdates() {
  return window['go']['main']['App']['AutoCheckForUpdates']();
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ClearActivity() {
  return window['go']['main']['App']['ClearActivity']();
}

export function ConnectDetectedIDEs() {
  return window['go']['main']['App']['ConnectDetectedIDEs']();
}

export function ConnectIDE(arg1) {
  return window['go']['main']['App']['ConnectIDE'](arg1);
}

export function DetectTelegramChat(arg1) {
  return window['go']['main']['App']['DetectTelegramChat'](arg1);
}

export function DisconnectIDE(arg1) {
  return window['go']['main']['App']['DisconnectIDE'](arg1);
}

export function DownloadUpdate(arg1) {
  return window['go']['main']['App']['DownloadUpdate'](arg1);
}

export function GetActivity() {
  return window['go']['main']['App']['GetActivity']();
}

export function GetIDESnippet(arg1) {
  return window['go']['main']['App']['GetIDESnippet'](arg1);
}

export function GetPublicURL() {
  return window['go']['main']['App']['GetPublicURL']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GetTelegramSettings() {
  return window['go']['main']['App']['GetTelegramSettings']();
}

export function GetWhatsAppSettings() {
  return window['go']['main']['App']['GetWhatsAppSettings']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function IsBridgeRunning() {
  return window['go']['main']['App']['IsBridgeRunning']();
}

export function ListIDEs() {
  return window['go']['main']['App']['ListIDEs']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function OpenDataFolder() {
  return window['go']['main']['App']['OpenDataFolder']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function ReadLogs() {
  return window['go']['main']['App']['ReadLogs']();
}

export function SaveTelegram(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveTelegram'](arg1, arg2, arg3, arg4);
}

export function SaveWhatsApp(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveWhatsApp'](arg1, arg2, arg3);
}

export function SendTestQuestion() {
  return window['go']['main']['App']['SendTestQuestion']();
}

export function SetAtDesk(arg1) {
  return window['go']['main']['App']['SetAtDesk'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartBridge() {
  return window['go']['main']['App']['StartBridge']();
}

export function StopBridge() {
  return window['go']['main']['App']['StopBridge']();
}
