// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddRecentChannel(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetRecentChannels():Promise<Array<main.RecentChannel>>;

export function HideWindow():Promise<void>;

export function IsBridgeRunning():Promise<boolean>;

export function KillExistingBridges():Promise<void>;

export function LoadConfig():Promise<string>;

export function QuitApp():Promise<void>;

export function ReadLogs():Promise<Array<string>>;

export function SaveConfig(arg1:string):Promise<string>;

export function ShowWindow():Promise<void>;

export function StartBridge():Promise<string>;

export function StopBridge():Promise<string>;
