// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HideWindow():Promise<void>;

export function IsBridgeRunning():Promise<boolean>;

export function LoadConfig():Promise<string>;

export function QuitApp():Promise<void>;

export function ReadLogs():Promise<Array<string>>;

export function SaveConfig(arg1:string):Promise<string>;

export function ShowWindow():Promise<void>;

export function StartBridge():Promise<string>;

export function StopBridge():Promise<string>;
